# Generated by Django 5.2.16 on 2026-07-23 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='demandes/photos/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='demandes.demandetravaux')),
            ],
            options={
                'verbose_name': 'Image de demande',
                'verbose_name_plural': 'Images de demandes',
                'db_table': 'demande_images',
                'ordering': ['ordre', 'created_at'],
            },
        ),
    ]
