# Generated by Django 5.2.16 on 2026-07-22 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0001_initial'),
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('prix_propose', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_disponibilite', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('retiree', 'Retirée')], default='en_attente', max_length=20)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='artisans.artisan')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='demandes.demandetravaux')),
            ],
            options={
                'db_table': 'propositions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('demande', 'artisan'), name='unique_proposition_par_artisan')],
            },
        ),
    ]
