# Generated by Django 5.2.16 on 2026-07-23 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='artisans/realisations/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Image principale du profil artisan')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='artisans.artisan')),
            ],
            options={
                'verbose_name': 'Image artisan',
                'verbose_name_plural': 'Images artisans',
                'db_table': 'artisan_images',
                'ordering': ['-is_primary', 'ordre', '-created_at'],
            },
        ),
    ]
